#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: false
#      routes:
#        # user-service
#        - id: user-service_route
#          uri: lb://USER-ADMINISTRATION
#          predicates:
#            - Path=/admin/users/**
#
#        # request-management
#        - id: request-management_route
#          uri: lb://REQUEST-MANAGEMENT
#          predicates:
#            - Path=/users/{userId}/requests/**
#
#        # event-management
#        - id: event-management_route
#          uri: lb://EVENT-MANAGEMENT
#          predicates:
#            - Path=/admin/categories/**, /categories/**, /admin/compilations/**, /compilations/**, /events/**, /admin/events/**, /users/{userId}/events/**
#
#        # comments
#        - id: comments_route
#          uri: lb://COMMENTS
#          predicates:
#            - Path=/admin/comments/**, /users/{userId}/events/{eventId}/comments/**, /public/events/{eventId}/comments/**

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true

server:
  port: 8080